services:
  spark-master:
    image: apache/spark-py
    ports:
      - '7077:7077'
      - '8080:8080'
    environment:
      - SPARK_MODE=master
    command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.master.Master', '--host', 'spark-master']

  spark-worker:
    image: apache/spark-py
    ports:
      - '8081:8081'
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: ['/opt/spark/bin/spark-class', 'org.apache.spark.deploy.worker.Worker', 'spark://spark-master:7077', '--work-dir', '/tmp']
